name: Publish NuGet Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Find and publish projects
        run: |
          set -e
          projects=$(find . -name "*.csproj")

          for project in $projects; do
            echo "Processing $project"
            version=$(xmllint --xpath "string(//Project/PropertyGroup/Version)" "$project")
            packageId=$(xmllint --xpath "string(//Project/PropertyGroup/PackageId)" "$project")

            if [ -z "$packageId" ]; then
              echo "No PackageId in $project, skipping..."
              continue
            fi

            echo "Checking if $packageId $version exists on NuGet..."
            if curl --silent --fail "https://api.nuget.org/v3-flatcontainer/${packageId,,}/${version}/${packageId,,}.nuspec" > /dev/null; then
              echo "$packageId $version already exists. Skipping publish."
              continue
            fi

            echo "Publishing $packageId $version..."
            dotnet pack "$project" -c Release
            dotnet nuget push "**/$packageId.$version.nupkg" \
              --api-key ${{ secrets.NUGET_API_KEY }} \
              --source https://api.nuget.org/v3/index.json \
              --skip-duplicate
          done
